### ISSUE TITLE
@JBean relationships

### ISSUE THREAD

**Issue by DHuckaby** [vbauer/jackdaw#1]
`@JBean`
`public class AbstractTypeA {`
`    protected boolean hasSomething;`
`}`

`@JBean`
`public class AbstractTypeB {`
`    protected TypeA type;`
`}`

The above example does not compile, it errors out because the TypeA class is not generated.

**Comment by vbauer** [comment]
@DHuckaby Thank you for issue. I hope it will be fixed in the next release.

**Comment by vbauer** [comment]
Fixed.
