### ISSUE TITLE
Upload to maven central

### ISSUE THREAD

**Issue by DHuckaby** [vbauer/jackdaw#2]
Your current solution doesn't look to be working correctly.

**Comment by vbauer** [comment]
Can't find mistake on my side, so I've just sent request to the author of Jitpack.io. I hope it will be fixed in the nearest future.

**Comment by DHuckaby** [comment]
I assume you are installing them directly to your local repo, correct? This would cause you to never actually see a problem. Remotely we can't see the jackdaw-apt or jackdaw-core repositories, only the parent one. This is a problem since it needs to be declared separately at build time. In looking at the parent jar that was downloaded it was empty, so it might be a configuration problem.

**Comment by vbauer** [comment]
Just to clarify: I checked it locally and even tried to remove directory ~/.m2/repository/com/github/vbauer before `mvn clean install` (to make clean test). As I said it works pretty fine on my side, but I have some problem with http://jitpack.io, so I still investigate this issue.

PS: 
* Actually Jitpack.io should make the same 'mvn clean install', after 'git clone...'.
* "Parent jar" is not JAR archive at all, it has "pom" packaging, but all JAR modules should be installed correctly.

**Comment by vbauer** [comment]
It looks like that we found temporary solution: https://github.com/vbauer/jackdaw/pull/4

Could you please try to use `jackdaw.jackdaw-core` and `jackdaw.jackdaw-apt` instead of `jackdaw-core` and `jackdaw-apt`?

**Comment by seanf** [comment]
It would still be good to get Jackdaw into Maven Central. Having jackdaw in Central would make it available for other Maven Central projects (which can't have non-Central dependencies). (From a quick glance, it appears that all of Jackdaw's own dependencies are in Maven Central.)

OSSRH is good for getting projects into Central, perhaps combined with Travis for running the builds: http://central.sonatype.org/pages/ossrh-guide.html
