### ISSUE TITLE
can u make a jar

### ISSUE THREAD

**Issue by jjhesk** [vbauer/jackdaw#5]
I would like to receive a jar to be included in the lib folder.

**Comment by vbauer** [comment]
You can build them using Maven or download from Maven repository:
* https://jitpack.io/com/github/vbauer/jackdaw/jackdaw-core/1.0.5/jackdaw-core-1.0.5.jar
* https://jitpack.io/com/github/vbauer/jackdaw/jackdaw-apt/1.0.5/jackdaw-apt-1.0.5.jar
